<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operational" nsURI="http://www.example.org/operational" nsPrefix="operational">
  <eClassifiers xsi:type="ecore:EClass" name="Operational">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalPerformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalPerformer" upperBound="-1"
        eType="#//Operational" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalArchitecture"
        upperBound="-1" eType="#//Operational" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalMethod" upperBound="-1"
        eType="#//Operational" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalParameter" upperBound="-1"
        eType="#//Operational" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalRole" upperBound="-1"
        eType="#//Operational" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
</ecore:EPackage>
