<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="strategic" nsURI="http://www.example.org/strategic" nsPrefix="strategic">
  <eClassifiers xsi:type="ecore:EClass" name="ActualEnduringTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;actualEnduringTask&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPhase" eType="#//ActualEnterprisePhase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActualEnterprisePhase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;enterprisePhase&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;abilityRole&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCapability" eType="#//Capability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnterpriseGoal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;enterpriseGoal&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enterprisePhase" upperBound="-1"
        eType="#//ActualEnterprisePhase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;strategic&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualEnduringTask" upperBound="-1"
        eType="#//ActualEnduringTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capablitityRole" upperBound="-1"
        eType="#//CapabilityRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enterpriseGoal" upperBound="-1"
        eType="#//EnterpriseGoal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capability" upperBound="-1"
        eType="#//Capability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;ability&quot;"/>
  </eClassifiers>
</ecore:EPackage>
